name: tests

on:
  [push, pull_request]

jobs:
  linting:
    name: tests
    runs-on: ubuntu-latest
    env:
      COV_PATH: coverage.txt

    steps:
      - name: Checkout the commit that triggered the workflow
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Set up env
        run: pip install -e ".[test]"

      - name: Run pytest
        run: pytest > ${{ env.COV_PATH }}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ${{ env.COV_PATH }}

      - name: Trigger coverage workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: trigger-coverage
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
